/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "dgbbwyztbqkystnjvkly"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRnYmJ3eXp0YnFreXN0bmp2a2x5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODUxNDYxNDAsImV4cCI6MjEwMDcyMjE0MH0.Ba-VHsM8IIVWUKpjN9IBN_Uil9V2ZQj-farGjA_om6o"